server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: create
    jpa:
      generate-ddl: true
      database-platform: org.hibernate.dialect.H2Dialect
department:
  service:
    url: http://localhost:9002/departments/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostname: localhost

